
flags = {
    "British": "🇬🇧",
    "German": "🇩🇪",
    "Brazilian": "🇧🇷",
    "French": "🇫🇷",
    "Dutch": "🇳🇱",
    "Finnish": "🇫🇮",
    "Australian": "🇦🇺",
    "Italian": "🇮🇹",
    "Austrian": "🇦🇹",
    "American": "🇺🇸",
    "Spanish": "🇪🇸",
    "Canadian": "🇨🇦",
    "Japanese": "🇯🇵",
    "Mexican": "🇲🇽",
    "Monégasque": "🇲🇨",
    "Thai": "🇹🇭",
    "Indian": "🇮🇳",
    "Danish": "🇩🇰",
    "Swedish": "🇸🇪",
    "Russian": "🇷🇺",
    "Venezuelan": "🇻🇪",
    "Argentine": "🇦🇷",
    "Belgian": "🇧🇪",
    "Monegasque": "🇲🇨",
    "Swiss": "🇨🇭",
    "Colombian": "🇨🇴",
    "South African": "🇿🇦",
    "Polish": "🇵🇱",
    "New Zealander": "🇳🇿",
}
